// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action.proto

package src.proto;

public final class ActionProtos {
  private ActionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code action.ActionType}
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * default value for empty variable
     * </pre>
     *
     * <code>UNKNOWN_ACTION_TYPE = 0;</code>
     */
    UNKNOWN_ACTION_TYPE(0),
    /**
     * <pre>
     * player actions
     * </pre>
     *
     * <code>SELECT_SET = 1;</code>
     */
    SELECT_SET(1),
    /**
     * <code>REQUEST_SHOW_SET = 2;</code>
     */
    REQUEST_SHOW_SET(2),
    /**
     * <code>LEAVE_GAME = 3;</code>
     */
    LEAVE_GAME(3),
    /**
     * <code>REQUEST_DRAW_THREE = 4;</code>
     */
    REQUEST_DRAW_THREE(4),
    /**
     * <pre>
     * not player actions
     * </pre>
     *
     * <code>SHOW_SET = 1000;</code>
     */
    SHOW_SET(1000),
    /**
     * <code>DRAW_THREE = 1001;</code>
     */
    DRAW_THREE(1001),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * default value for empty variable
     * </pre>
     *
     * <code>UNKNOWN_ACTION_TYPE = 0;</code>
     */
    public static final int UNKNOWN_ACTION_TYPE_VALUE = 0;
    /**
     * <pre>
     * player actions
     * </pre>
     *
     * <code>SELECT_SET = 1;</code>
     */
    public static final int SELECT_SET_VALUE = 1;
    /**
     * <code>REQUEST_SHOW_SET = 2;</code>
     */
    public static final int REQUEST_SHOW_SET_VALUE = 2;
    /**
     * <code>LEAVE_GAME = 3;</code>
     */
    public static final int LEAVE_GAME_VALUE = 3;
    /**
     * <code>REQUEST_DRAW_THREE = 4;</code>
     */
    public static final int REQUEST_DRAW_THREE_VALUE = 4;
    /**
     * <pre>
     * not player actions
     * </pre>
     *
     * <code>SHOW_SET = 1000;</code>
     */
    public static final int SHOW_SET_VALUE = 1000;
    /**
     * <code>DRAW_THREE = 1001;</code>
     */
    public static final int DRAW_THREE_VALUE = 1001;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ActionType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_ACTION_TYPE;
        case 1: return SELECT_SET;
        case 2: return REQUEST_SHOW_SET;
        case 3: return LEAVE_GAME;
        case 4: return REQUEST_DRAW_THREE;
        case 1000: return SHOW_SET;
        case 1001: return DRAW_THREE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return src.proto.ActionProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:action.ActionType)
  }

  public interface ActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:action.Action)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.action.ActionType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.action.ActionType type = 1;</code>
     * @return The type.
     */
    src.proto.ActionProtos.ActionType getType();

    /**
     * <code>int32 playerID = 2;</code>
     * @return The playerID.
     */
    int getPlayerID();

    /**
     * <code>repeated int32 cardPositions = 3;</code>
     * @return A list containing the cardPositions.
     */
    java.util.List<java.lang.Integer> getCardPositionsList();
    /**
     * <code>repeated int32 cardPositions = 3;</code>
     * @return The count of cardPositions.
     */
    int getCardPositionsCount();
    /**
     * <code>repeated int32 cardPositions = 3;</code>
     * @param index The index of the element to return.
     * @return The cardPositions at the given index.
     */
    int getCardPositions(int index);
  }
  /**
   * Protobuf type {@code action.Action}
   */
  public static final class Action extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:action.Action)
      ActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Action.newBuilder() to construct.
    private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Action() {
      type_ = 0;
      cardPositions_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Action();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Action(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              playerID_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                cardPositions_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              cardPositions_.addInt(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                cardPositions_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                cardPositions_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          cardPositions_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return src.proto.ActionProtos.internal_static_action_Action_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return src.proto.ActionProtos.internal_static_action_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              src.proto.ActionProtos.Action.class, src.proto.ActionProtos.Action.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.action.ActionType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.action.ActionType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public src.proto.ActionProtos.ActionType getType() {
      @SuppressWarnings("deprecation")
      src.proto.ActionProtos.ActionType result = src.proto.ActionProtos.ActionType.valueOf(type_);
      return result == null ? src.proto.ActionProtos.ActionType.UNRECOGNIZED : result;
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private int playerID_;
    /**
     * <code>int32 playerID = 2;</code>
     * @return The playerID.
     */
    @java.lang.Override
    public int getPlayerID() {
      return playerID_;
    }

    public static final int CARDPOSITIONS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.IntList cardPositions_;
    /**
     * <code>repeated int32 cardPositions = 3;</code>
     * @return A list containing the cardPositions.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getCardPositionsList() {
      return cardPositions_;
    }
    /**
     * <code>repeated int32 cardPositions = 3;</code>
     * @return The count of cardPositions.
     */
    public int getCardPositionsCount() {
      return cardPositions_.size();
    }
    /**
     * <code>repeated int32 cardPositions = 3;</code>
     * @param index The index of the element to return.
     * @return The cardPositions at the given index.
     */
    public int getCardPositions(int index) {
      return cardPositions_.getInt(index);
    }
    private int cardPositionsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (type_ != src.proto.ActionProtos.ActionType.UNKNOWN_ACTION_TYPE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (playerID_ != 0) {
        output.writeInt32(2, playerID_);
      }
      if (getCardPositionsList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(cardPositionsMemoizedSerializedSize);
      }
      for (int i = 0; i < cardPositions_.size(); i++) {
        output.writeInt32NoTag(cardPositions_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != src.proto.ActionProtos.ActionType.UNKNOWN_ACTION_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (playerID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerID_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < cardPositions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(cardPositions_.getInt(i));
        }
        size += dataSize;
        if (!getCardPositionsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        cardPositionsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof src.proto.ActionProtos.Action)) {
        return super.equals(obj);
      }
      src.proto.ActionProtos.Action other = (src.proto.ActionProtos.Action) obj;

      if (type_ != other.type_) return false;
      if (getPlayerID()
          != other.getPlayerID()) return false;
      if (!getCardPositionsList()
          .equals(other.getCardPositionsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerID();
      if (getCardPositionsCount() > 0) {
        hash = (37 * hash) + CARDPOSITIONS_FIELD_NUMBER;
        hash = (53 * hash) + getCardPositionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static src.proto.ActionProtos.Action parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.proto.ActionProtos.Action parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.proto.ActionProtos.Action parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.proto.ActionProtos.Action parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.proto.ActionProtos.Action parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static src.proto.ActionProtos.Action parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static src.proto.ActionProtos.Action parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.proto.ActionProtos.Action parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.proto.ActionProtos.Action parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static src.proto.ActionProtos.Action parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static src.proto.ActionProtos.Action parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static src.proto.ActionProtos.Action parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(src.proto.ActionProtos.Action prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code action.Action}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:action.Action)
        src.proto.ActionProtos.ActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return src.proto.ActionProtos.internal_static_action_Action_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return src.proto.ActionProtos.internal_static_action_Action_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                src.proto.ActionProtos.Action.class, src.proto.ActionProtos.Action.Builder.class);
      }

      // Construct using src.proto.ActionProtos.Action.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        playerID_ = 0;

        cardPositions_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return src.proto.ActionProtos.internal_static_action_Action_descriptor;
      }

      @java.lang.Override
      public src.proto.ActionProtos.Action getDefaultInstanceForType() {
        return src.proto.ActionProtos.Action.getDefaultInstance();
      }

      @java.lang.Override
      public src.proto.ActionProtos.Action build() {
        src.proto.ActionProtos.Action result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public src.proto.ActionProtos.Action buildPartial() {
        src.proto.ActionProtos.Action result = new src.proto.ActionProtos.Action(this);
        int from_bitField0_ = bitField0_;
        result.type_ = type_;
        result.playerID_ = playerID_;
        if (((bitField0_ & 0x00000001) != 0)) {
          cardPositions_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cardPositions_ = cardPositions_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof src.proto.ActionProtos.Action) {
          return mergeFrom((src.proto.ActionProtos.Action)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(src.proto.ActionProtos.Action other) {
        if (other == src.proto.ActionProtos.Action.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getPlayerID() != 0) {
          setPlayerID(other.getPlayerID());
        }
        if (!other.cardPositions_.isEmpty()) {
          if (cardPositions_.isEmpty()) {
            cardPositions_ = other.cardPositions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCardPositionsIsMutable();
            cardPositions_.addAll(other.cardPositions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        src.proto.ActionProtos.Action parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (src.proto.ActionProtos.Action) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.action.ActionType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.action.ActionType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.action.ActionType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public src.proto.ActionProtos.ActionType getType() {
        @SuppressWarnings("deprecation")
        src.proto.ActionProtos.ActionType result = src.proto.ActionProtos.ActionType.valueOf(type_);
        return result == null ? src.proto.ActionProtos.ActionType.UNRECOGNIZED : result;
      }
      /**
       * <code>.action.ActionType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(src.proto.ActionProtos.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.action.ActionType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int playerID_ ;
      /**
       * <code>int32 playerID = 2;</code>
       * @return The playerID.
       */
      @java.lang.Override
      public int getPlayerID() {
        return playerID_;
      }
      /**
       * <code>int32 playerID = 2;</code>
       * @param value The playerID to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerID(int value) {
        
        playerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 playerID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerID() {
        
        playerID_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList cardPositions_ = emptyIntList();
      private void ensureCardPositionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          cardPositions_ = mutableCopy(cardPositions_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 cardPositions = 3;</code>
       * @return A list containing the cardPositions.
       */
      public java.util.List<java.lang.Integer>
          getCardPositionsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(cardPositions_) : cardPositions_;
      }
      /**
       * <code>repeated int32 cardPositions = 3;</code>
       * @return The count of cardPositions.
       */
      public int getCardPositionsCount() {
        return cardPositions_.size();
      }
      /**
       * <code>repeated int32 cardPositions = 3;</code>
       * @param index The index of the element to return.
       * @return The cardPositions at the given index.
       */
      public int getCardPositions(int index) {
        return cardPositions_.getInt(index);
      }
      /**
       * <code>repeated int32 cardPositions = 3;</code>
       * @param index The index to set the value at.
       * @param value The cardPositions to set.
       * @return This builder for chaining.
       */
      public Builder setCardPositions(
          int index, int value) {
        ensureCardPositionsIsMutable();
        cardPositions_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cardPositions = 3;</code>
       * @param value The cardPositions to add.
       * @return This builder for chaining.
       */
      public Builder addCardPositions(int value) {
        ensureCardPositionsIsMutable();
        cardPositions_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cardPositions = 3;</code>
       * @param values The cardPositions to add.
       * @return This builder for chaining.
       */
      public Builder addAllCardPositions(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCardPositionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cardPositions_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cardPositions = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCardPositions() {
        cardPositions_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:action.Action)
    }

    // @@protoc_insertion_point(class_scope:action.Action)
    private static final src.proto.ActionProtos.Action DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new src.proto.ActionProtos.Action();
    }

    public static src.proto.ActionProtos.Action getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Action>
        PARSER = new com.google.protobuf.AbstractParser<Action>() {
      @java.lang.Override
      public Action parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Action(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Action> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Action> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public src.proto.ActionProtos.Action getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_action_Action_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_action_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014action.proto\022\006action\"S\n\006Action\022 \n\004type" +
      "\030\001 \001(\0162\022.action.ActionType\022\020\n\010playerID\030\002" +
      " \001(\005\022\025\n\rcardPositions\030\003 \003(\005*\223\001\n\nActionTy" +
      "pe\022\027\n\023UNKNOWN_ACTION_TYPE\020\000\022\016\n\nSELECT_SE" +
      "T\020\001\022\024\n\020REQUEST_SHOW_SET\020\002\022\016\n\nLEAVE_GAME\020" +
      "\003\022\026\n\022REQUEST_DRAW_THREE\020\004\022\r\n\010SHOW_SET\020\350\007" +
      "\022\017\n\nDRAW_THREE\020\351\007B\031\n\tsrc.protoB\014ActionPr" +
      "otosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_action_Action_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_action_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_action_Action_descriptor,
        new java.lang.String[] { "Type", "PlayerID", "CardPositions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
